# Generated by Django 6.0.5 on 2026-05-31 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(default='', max_length=15)),
                ('monthly_rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('join_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default='', max_digits=10)),
                ('status', models.CharField(choices=[('paid', 'paid'), ('unpaid', 'unpaid'), ('pending', 'pending')], max_length=20, null=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.tenant')),
            ],
        ),
    ]
